{
    "next": null,
    "count": null,
    "offset": null,
    "results": [
        {
        "external_id": "conservative",
        "readable_by": [
            "U01FZWMAFJ1XRH579Z662HG7Q10"
        ],
        "modifiable_by": [
            "U01FZWMAFJ1XRH579Z662HG7Q10",
            "U01FZT2QAHVK1Q1NEKN93PP574W"
        ],
        "id": "Y01G0EBF4C68KBW90BZMH32V2QD",
        "creation_datetime": "2022-04-12T07:40:34.053717+00:00",
        "version": 7,
        "version_datetime": "2022-08-09T11:08:55.204569+00:00",
        "version_authored_by_user_id": "U01FZT2QAHVK1Q1NEKN93PP574W",
        "deleted": false,
        "name": "Conservative",
        "parent_policy_id": null,
        "risk_profile_id": "K01G0EB2KB35J9E1VEKWEJZN1EC",
        "config": {
            "algorithm": "IVAR",
            "algorithm_version": 1,
            "algorithm_settings": {
            "execution_settings": {
                "base_currency": "USD",
                "fractional_shares": false,
                "cost_per_transaction_amount": 0,
                "cost_per_transaction_fraction": 0.005,
                "combine_transaction_cost_components": "MAX",
                "transaction_amount": [
                75,
                null
                ],
                "benchmark_id": null,
                "simulate_transaction_cost": false
            },
            "portfolio_update_constraints": {
                "min_portfolio_value": 500,
                "min_portfolio_update_optimality_improvement_fraction": 0.05,
                "max_portfolio_constraint_violation_pctpoints": 0.05,
                "holdings": {
                "cash_fraction": [
                    0.005,
                    0.05
                ]
                }
            },
            "portfolio_constraints": {
                "asset_classes": {
                "alternatives": [
                    0,
                    0
                ],
                "bonds": [
                    0.6,
                    0.8
                ],
                "commodities": [
                    0,
                    0.05
                ],
                "stocks": [
                    0.2,
                    0.25
                ],
                "cash": [
                    0,
                    0
                ],
                "corporate": null,
                "eurobond": null,
                "equity": null,
                "government": null,
                "money_market": null
                },
                "regions": {
                "bonds": {
                    "asia_pacific_developed": [
                    0,
                    0.2
                    ],
                    "emerging": [
                    0,
                    0.1
                    ],
                    "europe_developed": [
                    0,
                    0.2
                    ],
                    "north_america": [
                    0.6,
                    1
                    ]
                },
                "stocks": {
                    "asia_pacific_developed": [
                    0,
                    0.4
                    ],
                    "emerging": [
                    0,
                    0.1
                    ],
                    "europe_developed": [
                    0,
                    0.4
                    ],
                    "north_america": [
                    0.6,
                    1
                    ]
                }
                },
                "bond_types": {
                "convertible": [
                    0,
                    0.1
                ],
                "corporate": [
                    0,
                    0.5
                ],
                "government": [
                    0,
                    1
                ]
                },
                "sectors": {
                "basic_materials": [
                    0,
                    0.1
                ],
                "consumer_cyclical": [
                    0.1,
                    0.25
                ],
                "consumer_defensive": [
                    0,
                    0.2
                ],
                "communication_services": [
                    0,
                    0.1
                ],
                "energy": [
                    0,
                    0.05
                ],
                "financial_services": [
                    0.05,
                    0.2
                ],
                "healthcare": [
                    0.1,
                    0.25
                ],
                "industrials": [
                    0,
                    0.2
                ],
                "real_estate": [
                    0,
                    0.05
                ],
                "technology": [
                    0.25,
                    0.35
                ],
                "utilities": [
                    0,
                    0.1
                ]
                },
                "investment_universe": [
                    "BE97717W3319",
                    "BE97717W6049",
                    "BE4642871846",
                    "BE2330518539"
                ],
                "buy_universe": null,
                "holdings": {
                "position_amount": [
                    60,
                    100000
                ],
                "position_fraction": [
                    0.02,
                    0.2
                ],
                "cash_amount": [
                    10,
                    null
                ],
                "cash_fraction": [
                    0.0125,
                    0.03
                ]
                },
                "momentum": null
            },
            "benchmark_constraints": null,
            "model_portfolio_settings": null,
            "meta_portfolio_settings": null
            }
        }
        }
    ],
    "_embedded": {}
}