actor "Customer" as _c
participant "Broker/Custodian" as _b
participant "Client Middleware" as _m
participant "Integration API\nRobo Advisor Backend" as _a
participant "Optimizer API\nInvestSuite SaaS" as _o



== Onboarding ==
_m->_a:POST /users/
_m<--_a:user.id

_m->_a:GET /robo-advisor/policies/
_m<--_a: policy.id

_m->_a:POST /portfolios/\nwith user.id and policy.id
_m<--_a:portfolio.id

== Funding ==
_c->_b:cash
_c<--_b:funding OK

== Rebalancing  ==
loop Recurring Process
_m->_a:PATCH /portfolios/{id}
_a->_o:optimize()
_a<-_o:optimization
_m->_a:GET /portfolios/{portfoflio_id}/\noptimizations/{optimization_id}
_m<-_a:optimizations
_m->_b:place orders
_m<--_b:transactions
_m->_a:POST /portfolio/{id}/transactions
end
