actor "Customer" as _c
participant "Broker/Custodian" as _b
participant "Client Middleware" as _m
participant "Integration API\nRobo Advisor Backend" as _a
participant "Optimizer API\nInvestSuite SaaS" as _o


== Authentication ==
_m->_a:1. POST /auth/login
_m<--_a:token

== Onboarding ==
_m->_a:2. POST /users/
_m<--_a:user.id

_m->_a:3. GET /robo-advisor/policies/
_m<--_a: policy.id

_m->_a:3. POST /portfolios/\nwith user.id and policy.id
_m<--_a:portfolio.id

== Funding ==
_c->_b:Transfer cash\n(Simulated here by means\nof a paper portfolio)
_c<--_b:OK
_b->_m:Funding event
_m->_a:4. POST /portfolios/{id}/transactions/
_m->_a:4. PATCH /portfolios/{id}/

== Rebalancing  ==
loop Recurring process and triggered by a change in portfolio holdings
_a->_o:optimize()
_a<-_o:Optimization
_m->_a:5. GET /portfolios/{portfoflio_id}/\noptimizations/{optimization_id}
_m<-_a:Optimizations
_m->_b:Place orders
_m<--_b:Transactions
_m->_a:6. POST /portfolio/{id}/transactions
_m->_a:7. PATCH /portfolios/{id}/
end
