name: Publish GH Pages
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch repository
        run: git fetch --prune --unshallow

      - name: Set up runtime
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Publish docs
        run: |
          mkdocs gh-deploy --verbose --force
